-- MySQL Script generated by MySQL Workbench
-- Tue Mar 22 10:47:11 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Adresse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Adresse` (
  `idAdresse` INT NOT NULL AUTO_INCREMENT,
  `rue` VARCHAR(45) NOT NULL,
  `complement` VARCHAR(45) NULL,
  `codePostal` VARCHAR(45) NOT NULL,
  `ville` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAdresse`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Commerce`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Commerce` (
  `idCommerce` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `idAdresse` INT NOT NULL,
  PRIMARY KEY (`idCommerce`, `idAdresse`),
  INDEX `fk_Point_Vente_Adresse1_idx` (`idAdresse` ASC) VISIBLE,
  CONSTRAINT `fk_Point_Vente_Adresse1`
    FOREIGN KEY (`idAdresse`)
    REFERENCES `mydb`.`Adresse` (`idAdresse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Client` (
  `idClient` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `date_naissance` DATE NOT NULL,
  `telephone` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `mot_de_passe` VARCHAR(200) NOT NULL,
  `idAdresse` INT NOT NULL,
  `idCommerce` INT NOT NULL,
  PRIMARY KEY (`idClient`, `idAdresse`, `idCommerce`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_Client_Adresse1_idx` (`idAdresse` ASC) VISIBLE,
  INDEX `fk_Client_Point de Vente1_idx` (`idCommerce` ASC) VISIBLE,
  CONSTRAINT `fk_Client_Adresse1`
    FOREIGN KEY (`idAdresse`)
    REFERENCES `mydb`.`Adresse` (`idAdresse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Client_Point de Vente1`
    FOREIGN KEY (`idCommerce`)
    REFERENCES `mydb`.`Commerce` (`idCommerce`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ingredient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ingredient` (
  `idIngredient` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idIngredient`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Recette`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Recette` (
  `idRecette` INT NOT NULL AUTO_INCREMENT,
  `recette` LONGTEXT NOT NULL,
  PRIMARY KEY (`idRecette`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pizza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pizza` (
  `idPizza` INT NOT NULL AUTO_INCREMENT,
  `nom_pizza` VARCHAR(45) NOT NULL,
  `prix` FLOAT NOT NULL,
  `idRecette` INT NULL,
  PRIMARY KEY (`idPizza`),
  INDEX `fk_Pizza_Recette1_idx` (`idRecette` ASC) VISIBLE,
  UNIQUE INDEX `Recette_idRecette_UNIQUE` (`idRecette` ASC) VISIBLE,
  CONSTRAINT `fk_Pizza_Recette1`
    FOREIGN KEY (`idRecette`)
    REFERENCES `mydb`.`Recette` (`idRecette`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Etat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Etat` (
  `idEtat` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEtat`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Facture`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Facture` (
  `idFacture` INT NOT NULL AUTO_INCREMENT,
  `prix` FLOAT NOT NULL,
  `creation_date` DATETIME NOT NULL,
  PRIMARY KEY (`idFacture`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Commande`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Commande` (
  `idCommande` INT NOT NULL AUTO_INCREMENT,
  `idClient` INT NOT NULL,
  `idEtat` INT NOT NULL,
  `idFacture` INT NULL,
  PRIMARY KEY (`idCommande`, `idClient`, `idEtat`),
  INDEX `fk_Commande_Client1_idx` (`idClient` ASC) VISIBLE,
  INDEX `fk_Commande_Etat Commande1_idx` (`idEtat` ASC) VISIBLE,
  INDEX `fk_Commande_Facture1_idx` (`idFacture` ASC) VISIBLE,
  UNIQUE INDEX `Facture_idFacture_UNIQUE` (`idFacture` ASC) VISIBLE,
  CONSTRAINT `fk_Commande_Client1`
    FOREIGN KEY (`idClient`)
    REFERENCES `mydb`.`Client` (`idClient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Commande_Etat Commande1`
    FOREIGN KEY (`idEtat`)
    REFERENCES `mydb`.`Etat` (`idEtat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Commande_Facture1`
    FOREIGN KEY (`idFacture`)
    REFERENCES `mydb`.`Facture` (`idFacture`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Role` (
  `idRole` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idRole`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Employe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Employe` (
  `idEmploye` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `date_naissance` DATE NOT NULL,
  `telephone` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `mot_de_passe` VARCHAR(200) NOT NULL,
  `idRole` INT NOT NULL,
  `idAdresse` INT NOT NULL,
  `idCommerce` INT NOT NULL,
  PRIMARY KEY (`idEmploye`, `idRole`, `idAdresse`, `idCommerce`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_Employe_Role_idx` (`idRole` ASC) VISIBLE,
  INDEX `fk_Employe_Adresse1_idx` (`idAdresse` ASC) VISIBLE,
  INDEX `fk_Employe_Point de Vente1_idx` (`idCommerce` ASC) VISIBLE,
  CONSTRAINT `fk_Employe_Role`
    FOREIGN KEY (`idRole`)
    REFERENCES `mydb`.`Role` (`idRole`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Employe_Adresse1`
    FOREIGN KEY (`idAdresse`)
    REFERENCES `mydb`.`Adresse` (`idAdresse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Employe_Point de Vente1`
    FOREIGN KEY (`idCommerce`)
    REFERENCES `mydb`.`Commerce` (`idCommerce`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pizza_has_Commande`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pizza_has_Commande` (
  `idPizza` INT NOT NULL,
  `idCommande` INT NOT NULL,
  `quantité` INT NOT NULL,
  PRIMARY KEY (`idPizza`, `idCommande`),
  INDEX `fk_Pizza_has_Commande_Commande1_idx` (`idCommande` ASC) VISIBLE,
  INDEX `fk_Pizza_has_Commande_Pizza1_idx` (`idPizza` ASC) VISIBLE,
  CONSTRAINT `fk_Pizza_has_Commande_Pizza1`
    FOREIGN KEY (`idPizza`)
    REFERENCES `mydb`.`Pizza` (`idPizza`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pizza_has_Commande_Commande1`
    FOREIGN KEY (`idCommande`)
    REFERENCES `mydb`.`Commande` (`idCommande`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pizza_has_Ingredient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pizza_has_Ingredient` (
  `idPizza` INT NOT NULL,
  `idIngredient` INT NOT NULL,
  `quantite_g` FLOAT NOT NULL,
  PRIMARY KEY (`idPizza`, `idIngredient`),
  INDEX `fk_Pizza_has_Ingredient_Ingredient1_idx` (`idIngredient` ASC) VISIBLE,
  INDEX `fk_Pizza_has_Ingredient_Pizza1_idx` (`idPizza` ASC) VISIBLE,
  CONSTRAINT `fk_Pizza_has_Ingredient_Pizza1`
    FOREIGN KEY (`idPizza`)
    REFERENCES `mydb`.`Pizza` (`idPizza`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pizza_has_Ingredient_Ingredient1`
    FOREIGN KEY (`idIngredient`)
    REFERENCES `mydb`.`Ingredient` (`idIngredient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Stock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Stock` (
  `idStock` INT NOT NULL AUTO_INCREMENT,
  `unite_g` FLOAT NOT NULL,
  `prix_unitaire` FLOAT NOT NULL,
  `date_achat` DATE NOT NULL,
  `date_expiration` DATE NOT NULL,
  `quantite_unite` FLOAT NOT NULL,
  `idIngredient` INT NOT NULL,
  `idCommerce` INT NOT NULL,
  PRIMARY KEY (`idStock`, `idIngredient`, `idCommerce`),
  INDEX `fk_Stock_Ingredient1_idx` (`idIngredient` ASC) VISIBLE,
  INDEX `fk_Stock_Point_Vente1_idx` (`idCommerce` ASC) VISIBLE,
  CONSTRAINT `fk_Stock_Ingredient1`
    FOREIGN KEY (`idIngredient`)
    REFERENCES `mydb`.`Ingredient` (`idIngredient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Stock_Point_Vente1`
    FOREIGN KEY (`idCommerce`)
    REFERENCES `mydb`.`Commerce` (`idCommerce`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
